apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wxev
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wxev
    app.kubernetes.io/part-of: tkwch-fix-0075-0025-app
  name: devfile-sample-wxev
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wxev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wxev
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0025-tenant/tkwch-fix-0075-0025-app/devfile-sample-wxev@sha256:1a2cff46d34886979d5f66a3185108944127b0a2609d20cafecb67982d850dd0
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
